info:
  id: ${spring.application.name}

server:
  port: ${PORT:8761}

eureka:
  instance:
    instance-id: localhost:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    region: default
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    register-with-eureka: true

spring:
  zipkin:
    baseUrl: http://localhost:9411
    
security:
  basic:
    enabled: true
  user:
    name: secure-user
    password: secure-password
    
---
spring:
  profiles: peer1

eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://secure-user:secure-password@localhost:8762/eureka/

---
spring:
  profiles: peer2

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://secure-user:secure-password@localhost:8761/eureka/

    