server:
  port: ${PORT:8083}

spring:
  application:
    name: personalization-service
  redis:
    host: 127.0.0.1
    port: 6379
    
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    metadata-map:
        instance-id: localhost:${server.port}
  client:
    region: default
    registry-fetch-interval-seconds: 5