eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    hostname: ${vcap.application.uris[0]}
    prefer-ip-address: true
    ip-address: ${CF_INSTANCE_IP}
    non-secure-port: ${CF_INSTANCE_PORT}
    lease-renewal-interval-in-seconds: 15
  client:
    region: default
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    register-with-eureka: true
    service-url:
      defaultZone: ${vcap.services.discovery-service-peer1.credentials.uri}/eureka/,${vcap.services.discovery-service-peer2.credentials.uri}/eureka/
      
spring:
  zipkin:
    baseUrl: ${vcap.services.trace-monitoring-dashboard.credentials.uri}
     